name: sub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 환경변수로 출력 
      env:
        NAME: 'hojun.lee'
        AGE: 10
        HUMAN: true
        KEY: ${{ secrets.SECRET_KEY }}
        ID: ${{ github.actor }} 
      run: | 
        echo "내 이름은 $NAME, 내 아이디는 $ID 입니다. 제 나이는 $AGE이고, 휴먼 : $HUMAN 입니다."
        echo "$KEY"
